[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
github_client = { path = "../github_client" }
nextcloud_client = { path = "../nextcloud_client" }
tokio = { version = "1", features = ["full"] }
